### ISSUE TITLE
WifiProfiles and WifiAttack is still in the command list.

### ISSUE THREAD

**Issue by ExtremePro11299** [CrookedAlt/ExtraCommands#6]
Do not fix this issue by yourself but merge my pull request. If you fix it yourself, my pull request will have conflicts and I will have to make a new pull request. After merging my [pull request](#5), you can fix this issue.

----
WifiProfiles and WifiAttack is still in Commands.json and README.md after you have deleted their files.

**Comment by CrookedAlt** [comment]
Sorry i was gone for a WHILE but i want to thank you for your help, thanks. also i subbed to your yt
